import { mn } from "date-fns/locale";
import section_weight from "./section_weight";
import { h } from "vue";
import cast_spec from "./cast_spec";
import spec from "./spec";

export default {
    authorize: "Authorize",
    view: "View",
    save: "Save",
    update: "Update",
    cast_code: "Cast Code",
    bos_cast_code: "BOS Cast Code",
    long_cast_code: "Long Cast Code",
    quality_code: "Quality Code",
    table: {
        chemical_element: "Chemical Element",
        color_legend: "Color Legend:",
        in_range: "In Range",
        out_of_range: "Out of Range",
        not_required: "Not Required",
        compare_by: "Compare By",
        quality: "Quality",
        spec: "Spec",
        type: "Type",
        order_number: "Order Number",
        order_item_number: "Order Item Number",
        spec_code: "Spec Code",
        section_weight: "Section Weight",
        thickness: "Thickness",
        quality_code: "Quality Code",
        compare: "Compare",
        c:  "C",
        c_prec: "C Prec.",
        si: "Si",
        si_prec: "Si Prec.",
        mn: "Mn",
        mn_prec: "Mn Prec.",
        p: "P",
        p_prec: "P Prec.",
        s: "S",
        s_prec: "S Prec.",
        cr: "Cr",
        cr_prec: "Cr Prec.",
        mo: "Mo",
        mo_prec: "Mo Prec.",
        ni: "Ni",
        ni_prec: "Ni Prec.",
        al: "Al",
        al_prec: "Al Prec.",
        b:  "B",
        b_prec: "B Prec.",
        co: "Co",
        co_prec_n: "Co Prec.n",
        cu: "Cu",
        cu_prec: "Cu Prec.",
        nb: "Nb",
        nb_prec: "Nb Prec.",
        sn: "Sn",
        sn_prec: "Sn Prec.",
        ti: "Ti",
        ti_prec: "Ti Prec.",
        v:  "V",
        v_prec: "V Prec.",
        n:  "N",
        n_prec: "N Prec.",
        ca: "Ca",
        ca_prec: "Ca Prec.",
        solal: "SolAl",
        solal_prec: "SolAl Prec.",
        h:  "H",
        h_ppm_prec: "H PPM Prec.",
        as: "As",
        as_prec: "As Prec.",
        bi: "Bi",
        bi_prec: "Bi Prec.",
        ce: "Ce",
        ce_prec: "Ce Prec.",
        o:  "O",
        o_ppm_prec: "O PPM Prec.",
        pb: "Pb",
        pb_prec: "Pb Prec.",
        sb: "Sb",
        sb_prec: "Sb Prec.",
        w:  "W",
        w_prec: "W Prec.",
        zn: "Zn",
        zn_prec: "Zn Prec.",
        zr: "Zr",
        zr_prec: "Zr Prec.",
        te: "Te",
        te_prec: "Te Prec.",
        rad:  "Rad",
        rad_prec: "Rad Prec.",
        insal: "Insal",
        insal_prec: "Insal Prec.",
        n2: "N2",
        n2_prec: "N2 Prec.",
        cast_chemical_list: "Cast Chemical List",
        test_sample_id: "Test Sample ID",
        authorize_date: "Authorize Date",
        measure_match_id: "Measure Match ID",
        created_at: "Created At",
        updated_at: "Updated At",

        cast_spec: "Cast Spec",
        cast_code_bos_cast_code_quality_code: "Cast Code, Bos Cast Code, Quality Code",
        run_end_use: "Run end Use",
        cast_code:  "Cast Code",
        spec_code: "Spec Code",
        product_type_code: "Product Type Code",
        no_data_available: "No data available",
        
        semi:  "Semi",
        skelp_code: "Skelp Code",
        quantity: "Quantity",
    },
}

