import { mn } from "date-fns/locale";
import { ceil } from "xe-utils";

export default {
    table: {
        cast_code: "Cast Code",
        long_cast_code: "Long Cast Code",
        bos_cast_code: "BOS Cast Code",
        generation_code: "Generation Code",
        quality_code: "Quality Code",
        c:  "C",
        si: "Si",
        mn: "Mn",
        p: "P",
        s: "S",
        cr: "Cr",
        mo: "Mo",
        ni: "Ni",
        al: "Al",
        b:  "B",
        co: "Co",
        cu: "Cu",
        nb: "Nb",
        sn: "Sn",
        ti: "Ti",
        v:  "V",
        n:  "N",
        ca: "Ca",
        solal: "Solal",
        h:  "H",
        as: "As",
        bi: "Bi",
        ce: "Ce",
        o:  "O",
        pb: "Pb",
        sb: "Sb",
        w:  "W",
        zn: "Zn",
        zr: "Zr",
        te: "Te",
        rad:  "Rad",
        insal: "Insal",
        n2: "N2",
        created_at: "Created At",
        updated_at: "Updated At",
    },
    hint: "Cast Code. Bos Cast Code, Quality Code",
    delete_title: "Confirm to delete data?",
    delete_prompt: "Deleting is irreversible",
    delete_Cancel: "Cancel",
    deelte_conform: "Confirm",
    export: "Export",
    import: "Import",
    import_new: "Import new",


    edit: {
        add: "Add",
        edit: "Edit",
        Spec: "Spec",
        details: "Details",
        account: "Account",
        role: "Role",
        activated: "Activated",
        change_password: "Change Password:",
        old_password: "Old Password",
        default_team: "Default Team",
        manage_teams: "Managed Teams",
        manage_teams_hint: "Managed Teams if this is an owner or planner",
        new_password: "New Password",
        confirm_new_password: "Confirm New Password",
    }
}

