export default {
    table: {
        action:"Action",
        code: "Code",
        cast_code: "Cast Code",
        rolling_code: "Rolling Code",
        mults: "Mults",
        exist: "Exist",
        length: "Length(mm)",
        advice: "Advice",
        allocated_order_item: "Allocated Order Item",
        short_name: "Short Name",
        spec_code: "Spec Code",
        quantity: "Quantity",
        weight: "Weight(kg)",
        allocated_status: "Allocated Status",
        producttype_code: "Product Type Code",
        created_at: "Created At",
        defective_length: "Defective Length(mm)",
        bussiness_type: "Bussiness Type",
        store:  "Store",
        defective_piece: "Defective Piece",
        area_code: "Area Code",
        status: "Status",
        reserved_order_item: "Reserved Order Item",
        allocated_customer_name: "Reserved Customer Name",
        reserved_customer_no: "Reserved Customer No",
        reserved_customer_name: "Reserved Customer Name",
        compliance:  "Compliance",
        location: "Location",
        sawn_by: "Sawn By",
        defect: "Defect",
        load: "Load",
        rework_status: "Rework Status",
        reserve_status: "Reserve Status",
        rework_remarks: "Rework Remarks",
        hold_status: "Hold Status",
        hold_comment: "Hold Comment",
        comment:  "Comment",
        regrade_reason: "Regrade Reason",
        regrade_comment: "Regrade Comment",
        cover_status: "Cover Status",
        allocated_customer_no: "Allocated Customer No",
        runout_code: "Runout Code",
        cover_date: "Cover Date",
        sap_order_item: "SAP Order Item",
        cut_code: "Cut Code",
        full_name: "Full Name",
        auto_pass: "Auto Pass",
    },

    search_hint: "Search by code ",

    delete: {
        delete_title: "Delete this Site?",
        comform_delete: "Are you sure you would like to delete this Site?"
    },

    edit: {
        service_code: "Service Code",
        service_name: "Service Name",
        description: "Description",
        description_hint: "A description for your service."
    }
};
