export default {
    live_map: "Live Map",
    planner_chart: "Planner Chart",
    pickDrop_orders: "PickDrop Orders",
    order_download: "Order Download",
    jobs: "Jobs",
    my_jobs: "My Jobs",
    my_current: "My Current",
    my_finished: "My Finished",
    locations: "Locations",
    Locations: "Locations",
    location_group: "Location Group",
    LocationGroup: "Location Group",
    my_jobs: "My Jobs",
    workers: "Workers",
    worker_absence: "Worker Absence",
    team: "Teams",
    items: "Items",
    depots: "Depots",
    inventory: "Inventory",
    planner_service: "Planner_service",
    plugins_in_services: "Plugins In Services",
    plugins: "Plugins",
    login_accounts: "Login Accounts",
    route_service: "Route Service",
    setting: "Setting",
    my_order: "My Order",
    my_billing: "My Billing",
    Dashboard: "Dashboard",
    Jobs: "Jobs",
    Workers: "Workers",
    Inventory: "Inventory",
    Configuration: "Configuration",
    home: "Home",
    organization: "Organization",
    users: "Users",
    plugins: "Plugins",
    OpreationLog: "OpreationLog",
    Rolling: "Rolling",
    RollingList: "Rolling List",
    Order: "Order",
    product_spec: "Product Spec",
    charge_plan: "Charge Plan",
    Testing: "Testing",
    rolled_piece: "Rolled Piece",
    Site: "Site",
    Pens: "Pens",
    test_lab: "Test Lab",



    SiteAndArea: "SiteAndArea",
    site: "Site",
    area: "Area",
    Semi: "Semi",
    SemiList: "SemiList",
    SemiDetail: "SemiDetail",
    Spec: "Spec",
    SpecDetail: "SpecDetail",
    SpecList: "SpecList",
    ProductSpec: "ProductSpec",
};
