import { mn } from "date-fns/locale";
import { ceil } from "xe-utils";

export default {
    table: {
        mill_code: "Mill Code",
        rolling_seq: "Seq",
        rolling_code: "Rolling Code",
        year: "Year",
        week_number: "Week Number",
        semi_size: "Semi Size",
        rolling_status: "Status",
        comment: "Comment",
        programmed_start_date: "Programmed Date",
        duration_minutes: "Duration Hours(min)",
        additional_minutes: "Downtime(h)",
        programmed_tonnage: "Programmed Total Tons",
        ordered_tons: "Ordered Tons",
        updated_at: "Updated At",
        created_at: "Created At",
        updated_by: "Updated By"
    },
    product_size_code: "Product Size Code",
    export: "Export",
    export_to_ftp: "Export To FTP",
    import: "Import",
    import_from_ftp: "Import From FTP",
    delete_from_pc: "Delete from PC",
    send_to_pc: "Send to PC",
    start_date: "Start Date",
    end_date: "End Date",


    detail: {
        open_rolling: "Open Rolling",
        close_rolling: "Close Rolling",
        complete_rolling: "Complete Rolling",
        print_charge_list: "Print Charge List",
        allocate_blocks: "Allocate Blocks",
        order_group_list: "Order Group List",
        order_item_list: "Order Item List",
        rolling_number: "Rolling Number",
        rolling_number_placeholder: "Please enter the short code",
        rolling_code: "Rolling Code",
        mill: "Mill",
        mill_placeholder: "Please enter the mill",
        semi_size_placeholder: "Please enter the semi size",
        rolling_time_total: "Rolling Time Total",
        rolling_time_total_placeholder: "Please enter the rolling time total",
        open_time: "Open Time",
        complete_time: "Complete Time",
        programmed_tonnage_placeholder: "Please enter the programmed total",
        duration_minutes_placeholder: "Please enter the duration in minutes",
        programmed_start_date_placeholder: "Please enter the programmed date",
        week_number_placeholder: "Please enter the week",
        year_placeholder: "Please enter the year",
        mill_id_required: 'Mill is required.',
        product_size_id_required: 'Product Size is required.',
        rolling_time_total_required: 'Rolling Time Total is required.',
        product_class_code_required: 'Product Class is required.',
        product_category_code_required: 'Section Type is required.',
        rolling_code_required: 'Rolling Code is required.',
        short_code_required: 'Rolling Number is required.',
        rolling_dim1_required: 'Rolling Dim1 is required.',
        rolling_dim2_required: 'Rolling Dim2 is required.',
        rolling_dim3_required: 'Rolling Dim3 is required.',
        rolling_dim4_required: 'Rolling Dim4 is required.',
        semi_size_required: 'Semi Size is required.',
        rolling_status_required: 'Status is required.',
        programmed_start_date_required: 'Programmed Date is required.',
        duration_minutes_required: 'Duration in minutes is required.',
        programmed_tonnage_required: 'Programmed Total Tons is required.',
        completion_status: 'Completion Status'
    }
}

