export default {
    table: {
        semi_code: "Semi Code",
        please_enter_semi_code: "Please enter semi code",
        this_field_is_required: "This field is required",
        skelp_code: "Skelp Code",
        cast_code: "Cast Code",
        semi_status: "Semi Status",
        width: "Width(mm)",
        thickness: "Thickness(mm)",
        length: "Length(mm)",
        weight: "Weight(kg)",
        semi_load: "Semi Load",
        rolling:"Rolling",
        order_group: "Order Group",
        location: "Location",
        semi_charge_seq: "Semi Charge Seq",
        stock_in_date: "Stock In Date",
        select_time: "Select Time",
        semi_cut_seq: "Semi Cut Seq",
        quality_code: "Quality Code",
        scarfed_status: "Scarfed Status",
        scarfed_qty: "Scarfed QTY",
        semi_type: "Semi Type",
        defect:  "Defect",
        defect_qty: "Defect QTY",
        comment: "Comment",

        current_holds: "Current Holds",
        hold_code: "Hold Code",
        hold_type: "Hold Type",
        hold_name: "Hold Name",
        no_data_available: "No data available",
    },
}

