export default {
    table: {
        long_semi_code: "Long Semi Code",
        cast_code: "Cast Code",
        skelp_code: "Skelp Code",
        length: "Length(mm)",
        weight: "Weight(kg)",
        area:  "Area",
        position: "Position",
        thickness: "Thickness(mm)",
        quality_code: "Quality Code",
        rework:  "Rework",
        rework_comment: "Rework Comment",
        wagon_no: "Wagon No.",
        status: "Status",
        create_at: "Create At",
        type: "Type",
        hold: "Hold",
        generation_code: "Generation Code",
        quantity: "Quantity",
        defect_qty: "Defect QTY",
        scrap_qty: "Scrap QTY",
        width: "Width(mm)",
        current_allocated_rolling: "Current Allocated Rolling",
        current_allocated_block: "Current Allocated Block",
        defect: "Defect",
        hold_comment: "Hold Comment",
        comment: "Comment",
    },
    import_3rd_party_semi_and_cast: "Import 3rd Party Semi & Cast",
    Cancel: "Cancel",
    confirm: "Confirm",
    hold: "Hold",
    unhold: "Unhold",
    rework: "ReWork",
    rework_complete: "ReWork Complete",
    defect: "Defect",
    scrap: "Scrap",
    return: {
        do_you_confirm: "Do you confirm?",
        return_is_irreversible: "Return is irreversible",
    },
    hold_button: {
        semi_hold: "Semi Hold",
        list_of_selected: "List of selected",
        code: "Code",
        skelp_code: "Skelp Code",
        type: "Type",
        quality: "Quality",
        quantity: "Quantity",
        list_of_hold_type: "List of hold type",
        hold_reason: "Hold Reason",
        comment: "Comment",
    },
    unhold_button: {
        bar_unhold: "Bar Unhold",
        no_data_available: "No data available",
        code: "Code",
        hold_code: "Hold Code",
        hold_type: "Hold Type",
        list_of_hold_type: "List of hold type",
        comment: "Comment",
    },
    move_button:{
        move_to: "Move To",
        selected_list: "Selected List",
        site_type_no: "Site Type no.",
        site_no: "Site No.",
        area_no: "Area No.",
        position: "Position",
        are_you_sure_to_move_this_semi:  "Are you sure to move this semi?",
        close: "Close",
        save: "Save",
    },
    rework_button: {
        rework: "ReWork",
        defect_reason: "Defect Reason",
        semi_rework: "Semi ReWork",
        show_area: "Show Area",
        remarks: "Remarks",
        list_of_selected: "List of selected",
    },
    defect_button: {
        defective: "Defective",
        defect: "Defect",
        no_pieces: "No. Pieces",
        defect_reason: "Defect Reason",
        comment: "Comment",
    },
    scrap_button: {
        update: "Update",
        add: "Add",
        scrap: "Scrap",
        no_pcs: "No Pcs",
        scrap_comment: "Scrap Comment",
        reason: "Reason",
    },
    edit: {
        add: "Add",
        edit: "Edit",
        Semi: "Semi",
        details: "Details",
        account: "Account",
        role: "Role",
        activated: "Activated",
        change_password: "Change Password:",
        old_password: "Old Password",
        default_team: "Default Team",
        manage_teams: "Managed Teams",
        manage_teams_hint: "Managed Teams if this is an owner or planner",
        new_password: "New Password",
        confirm_new_password: "Confirm New Password",


    }
}

