export default {
  table: {
    search_by_section_size_code: "Search By Section Size Code",
    test_type: "Test Type",
    date_range: "Date Range",
    confirm: "Confirm",
    when: "When",
    test_id: "Test ID",
    test_type: "Test Type",
    created_by: "Created By",
    created_date: "Created Date",
    testing_machine: "Testing Machine",
    section_size_code: "Section Size Code",
    semi:  "Semi ID",
    kgm: "Kgm",
    impact_temp_c: "Impact Temp C",
    impact_temp_f: "Impact Temp F",
    impact_temp_units: "Impact Temp Units",
    impact_energy_1_j: "Impact Energy 1 J",
    impact_energy_2_j: "Impact Energy 2 J",
    impact_energy_3_j: "Impact Energy 3 J",
    impact_energy_average_j: "Impact Energy Average J",
    impact_energy_1_f:  "Impact Energy 1 F",
    impact_energy_2_f: "Impact Energy 2 F",
    impact_energy_3_f: "Impact Energy 3 F",
    impact_energy_average_f: "Impact Energy Average F",
    impact_shear_1: "Impact Shear 1",
    impact_shear_2: "Impact Shear 2",
    impact_shear_3: "Impact Shear 3",
    impact_shear_average: "Impact Shear Average",
    impact_impact_units: "Impact Impact Units",
    impact_energy_units: "Impact Energy Units",
    yield_low: "Tensile Yield Low(MPa)",
    elongation_code: "Tensile Elongation Code(percent)",
    elongation_a565: "Tensile Elongation A565(percent)",
    elongation_a200: "Tensile Elongation A200(percent)",
    elongation_a50: "Tensile Elongation A50(percent)",
    elongation_8: "Tensile Elongation 8 in(percent)",
    elongation_2: "Tensile Elongation 2 in(percent)",
    elongation_a80: "Tensile Elongation A80(percent)",
    r1_tested_thickness: "Tensile R1 Tested Thickness",
    r1_tested_width: "Tensile R1 Tested Width",
    r1_tested_diameter: "Tensile R1 Tested Diameter",
    r1_yield_tt0_5: "Tensile R1 Yield Rt0.5(MPa)",
    r1_yield_high: "Tensile R1 Yield High(MPa)",
    r1_yield_rp0_2: "Tensile R1 Yield Rp0.2(MPa)",
    r1_temp_c: "Impact R1 Temp C",
    r1_temp_f: "Impact R1 Temp F",
    r1_energy_1_j: "Impact R1 Energy 1 J",
    r1_energy_2_j: "Impact R1 Energy 2 J",
    r1_energy_3_j: "Impact R1 Energy 3 J",
    r1_energy_average_j: "Impact R1 Energy Average J",
    r1_energy_1_f: "Impact R1 Energy 1 F",
    r1_energy_2_f: "Impact R1 Energy 2 F",
    r1_energy_3_f: "Impact R1 Energy 3 F",
    r1_energy_average_f: "Impact R1 Energy Average F",
    r1_shear_1: "Impact R1 Shear 1",
    r1_shear_2: "Impact R1 Shear 2",
    r1_shear_3: "Impact R1 Shear 3",
    r1_shear_average: "Impact R1 Shear Average",
    r1_temp_units: "Impact R1 Temp Units",
    r1_impact_units: "Impact R1 Impact Units",
    r1_energy_units: "Impact R1 Energy Units",
    heat_treated_by: "Bend Heat Treated By",
    tested_by: "Bend Tested By",
    result_1: "Bend Result 1",
    result_2: "Bend Result 2",
    type: "Cleanness Type",
    k_number: "Cleanness K Number",
    k_value: "Cleanness K Value",
    bhn_min_max: "Hardness BHN Min/Max",
    ball_size_mm: "Hardness Ball Size (mm)",
    load_kg: "Hardness Load KG",
    hardness_1: "Hardness Hardness 1",
    hardness_2: "Hardness Hardness 2",
    hardness_3: "Hardness Hardness 3",
    hardness_4: "Hardness Hardness 4",
    hardness_5: "Hardness Hardness 5",
    hardness_av: "Hardness Hardness AV",
    decarburisation_min: "Decarburisation Min",
    decarburisation_max: "Decarburisation Max",
    decarburisation: "Decarburisation",
    spec_test: "Hydrogen Spec Test",
    rail_grade: "Hydrogen Rail Grade",
    max_test: "Hydrogen Max Test",
    max_resistivity: "Resistivity Max Resistivity",
    temperature: "Resistivity Temperature",
    temp: "Resistivity Temp",
    distance: "Resistivity Distance",
    volt: "Resistivity Volt",
    current: "Resistivity Current",
    resistivity: "Resistivity Resistivity",
    humidity: "Resistivity Humidity",
    sulphur_rail_grade: "Sulphur Rail Grade",
    tested_thickness: "Tensile Tested Thickness",
    tested_width: "Tensile Tested Width",
    tested_diameter: "Tensile Tested Diameter",
    yield_tt0_5: "Tensile Yield Rt0.5(MPa)",
    yield_high: "Tensile Yield High(MPa)",
    yield_rp0_2: "Tensile Yield Rp0.2(MPa)",
    yield_low: "Tensile Yield Low(MPa)",
    elongation_code: "Tensile Elongation Code(percent)",
    elongation_a565: "Tensile Elongation A565(percent)",
    elongation_a200: "Tensile Elongation A200(percent)",
    elongation_a50: "Tensile Elongation A50(percent)",
    elongation_8: "Tensile Elongation 8 in(percent)",
    elongation_2: "Tensile Elongation 2 in(percent)",
    elongation_a80: "Tensile Elongation A80(percent)",
    r1_tested_thickness: "Tensile R1 Tested Thickness",
    r1_tested_width: "Tensile R1 Tested Width",
    r1_tested_diameter: "Tensile R1 Tested Diameter",
    r1_yield_tt0_5: "Tensile R1 Yield Rt0.5(MPa)",
    r1_yield_high: "Tensile R1 Yield High(MPa)",
    r1_yield_rp0_2: "Tensile R1 Yield Rp0.2(MPa)",
    r1_yield_low: "Tensile R1 Yield Low(MPa)",
    r1_elongation_code: "Tensile R1 Elongation Code(percent)",
    r1_elongation_a565: "Tensile R1 Elongation A565(percent)",
    r1_elongation_a200: "Tensile R1 Elongation A200(percent)",
    r1_elongation_a50: "Tensile R1 Elongation A50(percent)",
    r1_elongation_8: "Tensile R1 Elongation 8 in(percent)",
    r1_elongation_2: "Tensile R1 Elongation 2 in(percent)",
    r1_elongation_a80: "Tensile R1 Elongation A80(percent)",
    r2_tested_thickness: "Tensile R2 Tested Thickness",
    r2_tested_width: "Tensile R2 Tested Width",
    r2_tested_diameter: "Tensile R2 Tested Diameter",
    r2_yield_tt0_5: "Tensile R2 Yield Rt0.5(MPa)",
    r2_yield_high: "Tensile R2 Yield High(MPa)",
    r2_yield_rp0_2: "Tensile R2 Yield Rp0.2(MPa)",
    r2_yield_low: "Tensile R2 Yield Low(MPa)",
    r1_yield_low: "Tensile R1 Yield Low(MPa)",
    r1_elongation_code: "Tensile R1 Elongation Code(percent)",
    r1_elongation_a565: "Tensile R1 Elongation A565(percent)",
    r1_elongation_a200: "Tensile R1 Elongation A200(percent)",
    r1_elongation_a50: "Tensile R1 Elongation A50(percent)",
    r1_elongation_8: "Tensile R1 Elongation 8 in(percent)",
    r1_elongation_2: "Tensile R1 Elongation 2 in(percent)",
    r1_elongation_a80: "Tensile R1 Elongation A80(percent)",
    r2_tested_thickness: "Tensile R2 Tested Thickness",
    r2_tested_width: "Tensile R2 Tested Width",
    r2_tested_diameter: "Tensile R2 Tested Diameter",
    r2_yield_tt0_5: "Tensile R2 Yield Rt0.5(MPa)",
    r2_yield_high: "Tensile R2 Yield High(MPa)",
    r2_yield_rp0_2: "Tensile R2 Yield Rp0.2(MPa)",
    r2_yield_low: "Tensile R2 Yield Low(MPa)",
    r2_elongation_code: "Tensile R2 Elongation Code(percent)",
    r2_elongation_a565: "Tensile R2 Elongation A565(percent)",
    r2_elongation_a200: "Tensile R2 Elongation A200(percent)",
    r2_elongation_a50: "Tensile R2 Elongation A50(percent)",
    r2_elongation_8: "Tensile R2 Elongation 8 in(percent)",
    r2_elongation_2: "Tensile R2 Elongation 2 in(percent)",
    r2_elongation_a80: "Tensile R2 Elongation A80(percent)",
    tensile_uts_mpa: "Tensile Tensile UTS (MPa)",
    r1_tensile_uts_mpa: "Tensile R1 Tensile UTS (MPa)",
    r2_tensile_uts_mpa: "Tensile R2 Tensile UTS (MPa)",
    result_c: "Prodan Result C",
    result_si: "Prodan Result Si",
    result_mn: "Prodan Result Mn",
    result_p: "Prodan Result P",
    result_s: "Prodan Result S",
    result_cr: "Prodan Result Cr",
    result_mo: "Prodan Result Mo",
    result_ni: "Prodan Result Ni",
    result_al: "Prodan Result Al",
    result_b: "Prodan Result B",
    result_co: "Prodan Result Co",
    result_cu: "Prodan Result Cu",
    result_nb: "Prodan Result Nb",
    result_sn: "Prodan Result Sn",
    result_ti: "Prodan Result Ti",
    result_v: "Prodan Result V",
    result_ca: "Prodan Result Ca",
    result_n2: "Prodan Result N2",
    result_o: "Prodan Result O",
    result_h: "Prodan Result H",
    result_sal: "Prodan Result Sal",
    result_as: "Prodan Result As",
    result_bi: "Prodan Result Bi",
    result_ce: "Prodan Result Ce",
    result_pb: "Prodan Result Pb",
    result_sb: "Prodan Result Sb",
    result_w: "Prodan Result W",
    result_zn: "Prodan Result Zn",
    result_zr: "Prodan Result Zr",
    uuid: "UUID",
    confirm_at: "Confirm at",
    confirm_by: "Confirm by",
    created_at: "Created At",
    created_by: "Created By",
    update_name: "Updater",
    updated_at: "Updated At",
    update_by: "Updated By"
  },
  test: "Test",
  delete: {
    delete_title: "Delete Service?",
    comform_delete: "Are you sure you would like to delete this service?"
  },

  search_hint: "Search by code, name, description",

  edit: {
    service_code: "Service Code",
    service_name: "Service Name",
    description: "Description",
    description_hint: "A description for your service."
  }
};
