import { result } from "lodash";
import section_type from "./section_type";

export default {
  table: {
    save: "Save",
    update: "Update",
    search_by_test_code: "Search By Test Code",
    type: "Type",
    result_status: "Result Status",
    test_status: "Test Status",
    standard: "Standard",
    time_range: "Time Range",
    auto_pass: "Auto Pass",
    test_code: "Test Code",
    long_cast_code: "Long Cast Code",
    cast_code: "Cast Code",
    ref: "Ref",
    sample: "Sample",
    runout: "Runout",
    rolling: "Rolling",
    spec: "Spec",
    standard: "Standard",
    inspector_1: "Inspector 1",
    inspector_2: "Inspector 2",
    inspector_3: "Inspector 3",
    inspector_4: "Inspector 4",
    status: "Status",
    print_status: "Print Status",
    tester_initials: "Tester Initials",
    kg: "Kg/m",
    tensile_loc: "Tensile Loc",
    yield: "Yield",
    uts: "UTS(MPa)",
    elongation: "Elongation",
    elongation_code: "Elongation Code",
    yield_ratio: "Yield/UTS Ratio",
    impart_temp: "Impart Temp",
    impart_unit: "Impart Unit",
    temp_unit: "Temp Unit",
    energy_1:  "Energy 1",
    energy_2:  "Energy 2",
    energy_3:  "Energy 3",
    energy_average:  "Energy Average",
    bend_result: "Bend Result",
    created_at: "Created at",
    updated_at: "Updated at",
  },
  detail: {
    covered_products: "Covered Products",
    finished_product_code: "Finished Product Code",
    test_code: "Test Code",
    covered_weight_kg: "Covered Weight Kg",
    covered_quantity: "Covered Quantity",
    retest_2: "Retest 2",
    cast: "Cast",
    type: "Type",
    temp: "Temp(°C)",
    nominated_time: "Nominated Time",
    test_result: "Test Result",
    test_code: "Test Code",
    test_ref:  "Test Ref",
    test_ref_rt2: "Test Ref Rt2",
    long_cast_code: "Long Cast Code",
    status: "Status",
    print_status: "Print Status",
    test_standard: "Test Standard",
    type:  "Type",
    spec_requirements: "Spec Requirements",
    test_impact: "Test Impact",
    check_digit_0: "Check Digit 0",
    testing_machine: "Testing Machine",
    temperature_f:  "Temperature F",
    temperature_c:  "Temperature C",
    energy_1_j: "Energy 1 J",
    energy_2_j: "Energy 2 J",
    energy_3_j: "Energy 3 J",
    energy_average_j: "Energy Average J",
    energy_1_f: "Energy 1 F",
    energy_2_f:   "Energy 2 F",
    energy_3_f:   "Energy 3 F",
    energy_average_f:   "Energy Average F",
    shear_1: "Shear 1",
    shear_2: "Shear 2",
    shear_3: "Shear 3",
    shear_average: "Shear Average",
    tested_by: "Tested By",
    impact_size: "Impact Size",
    retest_1: "Retest 1",
    check_digit_1: "Check Digit 1",
    check_digit_2: "Check Digit 2",
    energy_j: "Energy J",
    energy_average_j: "Energy Average J",
    energy_1_f: "Energy F",
    energy_average_f: "Energy Average F",
    spec_unit: "Spec Unit",
    avg_min: "Avg Min",
    ind_max: "Ind Max",
    tensile_min:  "Tensile Min",
    tensile_max: "Tensile Max",
    yield_min: "Yield Min",
    yield_max: "Yield Max",
    y_min:  "Y/T Min",
    y_max: "Y/T Max",
    elongation_code: "Elongation Code",
    elongation_min: "Elongation Min",
    test_tensile_result: "Test Tensile Result",
    measured_thickness: "Measured Thickness",
    measured_width: "Measured Width",
    measured_diameter: "Measured Diameter",
    yield_rt: "Yield Rt0.5(MPa)",
    yield_high: "Yield High(MPa)",
    yield_rp: "Yield Rp0.2(MPa)",
    yield_low: "Yield Low(MPa)",
    yield: "Yield(MPa)",
    uts_mpa: "UTS MPA",
    elongation: "Elongation(percent)",
    elongation_a565: "Elongation A565(percent)",
    elongation_a200: "Elongation A200(percent)",
    elongation_a50: "Elongation A50(percent)",
    elongation_a80: "Elongation A80(percent)",
    elongation_8_in: "Elongation 8 In(percent)",
    elongation_2_in: "Elongation 2 In(percent)",
    testing_machine: "Testing Machine",
    reduction_of_area: "Reduction Of Area",
    cross_seational_area: "Cross Seational Area",
    area: "Area",
    test_standard: "Test Standard",
    tested_by: "Tested By",
    test_bend: "Test Bend",
    code: "Code",
    heat_treated_by: "Heat Treated By",
    result: "Result",
    spec_requirements: "Spec Requirements",
    k_value_max: "K Value Max",
    k_number: "K Number",
    test_requirements: "Test Requirements",
    k_oxide: "K Oxide",
    decarb_value_max: "Decarb Value Max",
    section: "Section",
    section_size_code: "Section Size Code",
    bloom: "Bloom",
    inspection_authority_code: "Inspection Authority Code",
    kg: "Kg",
    max:   "Max",
    decarburisation: "Decarburisation",
    decarburisation_min: "Decarburisation Min",
    decarburisation_max: "Decarburisation Max",
    decarb: "Decarb",
    test_hardness: "Test Hardness",
    bhn: "BHN MIN/MAX",
    ball_size:  "Ball Size(mm)",
    load_kg: "Load Kg",
    hardness_1: "Hardness 1",
    hardness_2: "Hardness 2",
    hardness_3: "Hardness 3",
    hardness_4: "Hardness 4",
    hardness_5: "Hardness 5",
    hardness_avg_unit: "Hardness Avg Unit(HBW)",
    test_hydrogen: "Test Hydrogen",
    max_test: "Max Test",
    rail_grade: "Rail Grade",
    spec_test: "Spec Test",
    result_c: "Result C",
    result_si:  "Result Si",
    result_mn: "Result Mn",
    result_p:  "Result P",
    result_s:  "Result S",
    result_cr: "Result Cr",
    result_mo: "Result Mo",
    result_ni: "Result Ni",
    result_al:  "Result Ai",
    result_cu: "Result Cu",
    result_co: "Result Co",
    result_b:  "Result B",
    result_nb: "Result Nb",
    result_v:  "Result V",
    result_sn:  "Result Sn",
    result_ti: "Result Ti",
    result_ca: "Result Ca",
    result_n2: "Result N2",
    result_o: "Result O",
    result_h: "Result H",
    result_sal: "Result Sal",
    result_as: "Result As",
    result_bi: "Result Bi",
    result_ce: "Result Ce",
    result_pb: "Result Pb",
    result_sb: "Result Sb",
    result_w: "Result W",
    result_zn: "Result Zn",
    result_zr: "Result Zr",
    max_resistivity: "Max Resistivity",
    test_resistivity: "Test Resistivity",
    temperature: "Temperature(C)",
    humidity: "Humidity(%)",
    distance: "Distance(mm)",
    voit:  "Voit(V)",
    current: "Current(A)",
    resistivity_mo: "Resistivity(mo cm)",
    correction_factor: "Correction Factor",
    correct_resistivity: "Correct Resistivity(mo cm)",
    sulphur_print_max: "Sulphur Print Max",
    d_val: "D Val",
    in_spec: "In Spec",
    test_decarburization:  "Test Decarburization",
    test_prodan: "Test Prodan",
    test_sulphur: "Test Sulphur",
    updated_at: "Updated At",
    updater:   "Updater",
    update_reason: "Update Reason",
    tester: "Tester",
    created_at: "Created At",
    comment: "Comment",
  },
  test: "Test",
  delete: {
    delete_title: "Delete Service?",
    comform_delete: "Are you sure you would like to delete this service?"
  },

  search_hint: "Search by code, name, description",

  edit: {
    service_code: "Service Code",
    service_name: "Service Name",
    description: "Description",
    description_hint: "A description for your service."
  }
};
