// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/layouts/AdminLayout.vue')['default']
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppToolbar: typeof import('./src/components/AppToolbar.vue')['default']
    AppToolbarEnvStepResult: typeof import('./src/components/AppToolbarEnvStepResult.vue')['default']
    AppToolbarHealthCheck: typeof import('./src/components/AppToolbarHealthCheck.vue')['default']
    // AppToolbarLiveMap: typeof import('./src/components/AppToolbarLiveMap.vue')['default']
    AppToolbarLiveMapTaixInfo: typeof import('./src/components/AppToolbarLiveMapTaixInfo.vue')['default']
    AppToolbarPlannerScore: typeof import('./src/components/AppToolbarPlannerScore.vue')['default']
    AuthLayout: typeof import('./src/components/layouts/AuthLayout.vue')['default']
    BusinessHours: typeof import('./src/components/vue_business_hours_update/components/BusinessHours.vue')['default']
    BusinessHoursDatalist: typeof import('./src/components/vue_business_hours_update/components/BusinessHoursDatalist.vue')['default']
    BusinessHoursDay: typeof import('./src/components/vue_business_hours_update/components/BusinessHoursDay.vue')['default']
    BusinessHoursSelect: typeof import('./src/components/vue_business_hours_update/components/BusinessHoursSelect.vue')['default']
    DatePickerMenu: typeof import('./src/components/DatePickerMenu.vue')['default']
    DefaultLayout: typeof import('./src/components/layouts/DefaultLayout.vue')['default']
    FlexForm: typeof import('./src/components/FlexForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    JobCheckDialog: typeof import('./src/components/JobCheckDialog.vue')['default']
    JobsStatusWaringDialog: typeof import('./src/components/JobsStatusWaringDialog.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    Refresh: typeof import('./src/components/Refresh.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusDialog: typeof import('./src/components/StatusDialog.vue')['default']
    StatWidget: typeof import('./src/components/StatWidget.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TimePickerMenu: typeof import('./src/components/TimePickerMenu.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
