import { mn } from "date-fns/locale";
import { ceil } from "xe-utils";

export default {
    table: {
        cast_code: "铸件编码",
        long_cast_code: "完整铸件编码",
        bos_cast_code: "基础氧气炼钢铸件编码",
        generation_code: "生产批次号",
        quality_code: "质量编码",
        c: "C(碳)",
        si: "Si(硅)",
        mn: "Mn(锰)",
        p: "P(磷)",
        s: "S(硫)",
        cr: "Cr(铬)",
        mo: "Mo(钼)",
        ni: "Ni(镍)",
        al: "Al(铝)",
        b:  "B(硼)",
        co: "Co(钴)",
        cu: "Cu(铜)",
        nb: "Nb(铌)",
        sn: "Sn(锡)",
        ti: "Ti(钛)",
        v: "V(钒)",
        n: "N(氮)",
        ca: "Ca(钙)",
        solal: "可溶铝 (Sol.Al)",
        h: "H(氢)",
        as: "As(砷)",
        bi: "Bi(铋)",
        ce: "Ce(铈)",
        o: "O(氧)",
        pb: "Pb(铅)",
        sb: "Sb(锑)",
        w: "W(钨)",
        zn: "Zn(锌)",
        zr: "Zr(锆)",
        te: "Te(碲)",
        rad: "RAD(稀土)",
        insal: "不可溶铝 (Ins.Al)",
        n2: "N2(氮气)",
        created_at: "创建时间",
        updated_at: "更新时间",
    },
    hint: "铸件，基础氧气炼钢铸造代码，质量编码",
    delete_title: "确认要删除数据吗？",
    delete_prompt: "删除是不可逆的",
    delete_Cancel: "取消",
    deelte_conform: "确认",
    export: "导出",
    import: "导入",
    import_new: "新的导入",
    edit: {
        add: "添加",
        edit: "编辑",
        user: "账户",
        details: "详情",
        account: "账户",
        role: "角色",
        activated: "是否可用",
        change_password: "更改密码:",
        old_password: "旧密码",
        default_team: "默认团队",
        manage_teams: "管理团队",
        manage_teams_hint: "Managed Teams if this is an owner or planner",
        new_password: "新密码",
        confirm_new_password: "确认新密码",



    }
}