export default {
    table: {
        action: "操作",
        code: "名称",
        cast_code: "铸件代码",
        rolling_code: "轧制计划",
        mults: "倍数",
        exist: "库存数量",
        length: "长度 (mm)",
        advice: "建议",
        allocated_order_item: "分配订单项",
        short_name: "简称",
        spec_code: "规格代码",
        quantity: "数量",
        weight: "重量 (kg)",
        allocated_status: "分配状态",
        producttype_code: "产品类型编号",
        created_at: "创建时间",
        defective_length: "缺陷长度 (mm)",
        bussiness_type: "业务类型",
        store: "仓库",
        defective_piece: "缺陷件数",
        area_code: "区域编号",
        status: "状态",
        reserved_order_item: "预留订单项",
        reserved_customer_no: "预留客户编号",
        reserved_customer_name: "预留客户名称",
        allocated_customer_name: "分配客户名称",
        allocated_customer_no: "分配客户编号",
        compliance: "合规性",
        location: "位置",
        sawn_by: "锯切操作员",
        defect: "缺陷",
        load: "载荷",
        rework_status: "返工状态",
        reserve_status: "预留状态",
        rework_remarks: "返工备注",
        hold_status: "保留状态",
        hold_comment: "保留备注",
        comment: "备注",
        regrade_reason: "重新评级原因",
        regrade_comment: "重新评级备注",
        cover_status: "覆盖状态",
        runout_code: "钢坯",
        cover_date: "覆盖日期",
        sap_order_item: "SAP 订单项",
        cut_code: "切割编号",
        full_name: "全名",
        auto_pass: "自动通过",
    },

    search_hint: "按名称搜索",

    delete: {
        delete_title: "删除此记录？",
        confirm_delete: "您确定要删除此记录吗？"
    },

    edit: {
        service_code: "服务代码",
        service_name: "服务名称",
        description: "描述",
        description_hint: "服务的描述。"
    }
};