export default {
    live_map: "实时地图",
    planner_chart: "甘特图",
    pickDrop_orders: "取送订单",
    order_download: "订单下载",
    jobs: "任务",
    my_jobs: "我的任务",
    my_current: "当前任务",
    my_finished: "已完成任务",
    locations: "地址",
    Locations: "地址",
    location_group: "地址组",
    LocationGroup: "地址组",
    Workers: "组织结构",
    workers: "员工",
    worker_absence: "员工请假",
    team: "团队",
    items: "物品",
    depots: "仓库",
    inventory: "库存",
    planner_service: "调度服务",
    plugins_in_services: "插件服务",
    plugins: "插件管理",
    login_accounts: "账户管理",
    route_service: "Route Service",
    setting: "系统设置",
    my_order: "我的订单",
    my_billing: "我的账单",
    Dashboard: "业务看板",
    Jobs: "任务",
    Inventory: "仓库",
    Configuration: "配置",
    home: "首页",
    organization: "组织配置",
    users: "用户管理",
    OpreationLog: "操作日志",
    Rolling: "Rolling",
    Order: "订单",
    RollingList: "生产计划列表",
    product_spec: "Product Spec",
    charge_plan: "Charge Plan",
    Testing: "Testing",
    rolled_piece: "Rolled Piece",
    Site: "Site",
    Pens: "Pens",
    test_lab: "Test Lab",
    SiteAndArea: "园区",
    site: "场地",
    area: "地区",
    Semi: "备料",
    SemiList: "备料列表",
    SemiDetail: "备料详情",
    Spec: "规格详情",
    SpecDetail: "规格详情",
    SpecList: "规格列表",
    ProductSpec: "产品规格",
};
