import { mn } from "date-fns/locale";
import { ceil } from "xe-utils";

export default {
    table: {
        mill_code: "工厂",
        rolling_seq: "轧制序列",
        rolling_code: "轧制计划",
        year: "年",
        week_number: "周",
        semi_size: "成品尺寸",
        rolling_status: "状态",
        comment: "备注",
        programmed_start_date: "计划日期",
        duration_minutes: "持续时长（分钟）",
        additional_minutes: "额外停机时间（小时）",
        programmed_tonnage: "计划总吨数",
        ordered_tons: "订购吨数",
        updated_at: "更新时间",
        created_at: "创建时间",
        updated_by: "更新者"
    },
    product_size_code: "产品尺寸",
    export: "导出",
    export_to_ftp: "导出到FTP",
    import: "导入",
    import_from_ftp: "从FTP导入",
    delete_from_pc: "从工控机删除",
    send_to_pc: "发送至工控机",
    start_date: "开始日期",
    end_date: "结束日期",


    detail: {
        open_rolling: "开启轧制",
        close_rolling: "关闭轧制",
        complete_rolling: "完成轧制",
        print_charge_list: "分配半成品列表",
        allocate_blocks: "分配订单组",
        order_group_list: "订单组列表",
        order_item_list: "订单项列表",
        rolling_number: "轧制编号",
        rolling_number_placeholder: "请输入轧制编号",
        rolling_code: "轧制计划",
        mill: "工厂",
        mill_placeholder: "请输入工厂名称",
        semi_size_placeholder: "请输入半成品尺寸",
        rolling_time_total: "总轧制时间",
        rolling_time_total_placeholder: "请输入总轧制时间",
        open_time: "开启时间",
        complete_time: "完成时间",
        programmed_tonnage_placeholder: "请输入计划总吨数",
        duration_minutes_placeholder: "请输入持续时长（分钟）",
        programmed_start_date_placeholder: "请输入计划日期",
        week_number_placeholder: "请输入周数",
        year_placeholder: "请输入年份",
        mill_id_required: "工厂编号是必需的。",
        product_size_id_required: "产品尺寸是必需的。",
        rolling_time_total_required: "总轧制时间是必需的。",
        product_class_code_required: "产品类别是必需的。",
        product_category_code_required: "型材类型是必需的。",
        rolling_code_required: "轧制代码是必需的。",
        short_code_required: "轧制编号是必需的。",
        rolling_dim1_required: "dim1是必需的。",
        rolling_dim2_required: "dim2是必需的。",
        rolling_dim3_required: "dim3是必需的。",
        rolling_dim4_required: "dim4是必需的。",
        semi_size_required: "半成品尺寸是必需的。",
        rolling_status_required: "状态是必需的。",
        programmed_start_date_required: "计划日期是必需的。",
        duration_minutes_required: "持续时长（分钟）是必需的。",
        programmed_tonnage_required: "计划总吨位是必需的。",
        completion_status: '完成状态'
    }
}

