import { mn } from "date-fns/locale";
export default {
    table: {
        long_semi_code: "半成品",
        cast_code: "铸件",
        skelp_code: "制管钢板",
        length: "长度(mm)",
        weight: "重量(kg)",
        area:  "截面积",
        position: "状态(位置)",
        thickness: "厚度(mm)",
        quality_code: "质量编码",
        rework:  "再加工",
        rework_comment: "再加工建议",
        wagon_no: "车辆编号",
        status: "状态",
        create_at: "创建时间",
        type: "类型",
        hold: "暂停",
        generation_code: "代次",
        quantity: "数量",
        defect_qty: "缺陷数量",
        scrap_qty: "废料数量",
        width: "宽度(mm)",
        current_allocated_rolling: "已分配轧制计划",
        current_allocated_block: "已分配订单组",
        defect: "缺陷",
        hold_comment: "暂停批注",
        comment: "批注",
    },
    import_3rd_party_semi_and_cast: "导入第三方半成品和铸件",
    Cancel: "取消",
    confirm: "确定",
    hold: "暂停",
    unhold: "取消暂停",
    rework: "再加工",
    rework_complete: "再加工完成",
    defect: "缺陷",
    scrap: "废料",
    return: {
        do_you_confirm: "你确认了吗？",
        return_is_irreversible: "返回是不可逆的",
    },
    hold_button: {
        semi_hold: "暂停半成品",
        list_of_selected: "选中列表",
        code: "编号",
        skelp_code: "制管钢板",
        type: "类型",
        quality: "质量编码",
        quantity: "数量",
        list_of_hold_type: "暂停类型",
        hold_reason: "暂停原因",
        comment: "批注",
    },
    unhold_button: {
        bar_unhold: "取消暂停半成品",
        no_data_available: "没有可用的数据",
        code: "编号",
        hold_code: "暂停编号",
        hold_type: "暂停类型",
        list_of_hold_type: "暂停类型",
        comment: "批注",
    },
    move_button:{
        move_to: "移动到",
        selected_list: "选中列表",
        site_type_no: "场地类型编号",
        site_no: "场地编号",
        area_no: "区域编号",
        position: "状态(位置)",
        are_you_sure_to_move_this_semi:  "你确定要移动这个半成品吗?",
        close: "关闭",
        save: "保存",
    },
    rework_button: {
        rework: "再加工",
        defect_reason: "缺陷原因",
        semi_rework: "半成品再加工",
        list_of_selected: "选中列表",
        show_area: "显示区域",
        remarks: "备注",
    },
    defect_button: {
        defective: "有缺陷的",
        defect: "缺陷",
        no_pieces: "部件",
        defect_reason: "缺陷原因",
        comment: "备注",
    },
    scrap_button: {
        update: "更新",
        add: "添加",
        scrap: "废料",
        no_pcs: "部件",
        scrap_comment: "废料批注",
        reason: "原因",
    }
}
