export default {
    table: {
        semi_code: "半成品",
        please_enter_semi_code: "请输入半成品编号",
        this_field_is_required: "此字段是必填项",
        skelp_code: "制管钢板",
        cast_code: "铸件",
        semi_status: "半成品状态",
        width: "宽度(mm)",
        thickness: "厚度(mm)",
        length: "长度(mm)",
        weight: "重量(kg)",
        semi_load: "半成品负载",
        rolling:"轧制计划",
        order_group: "订单组",
        location: "位置",
        semi_charge_seq: "半成品存储序列",
        stock_in_date: "入库时间",
        select_time: "选择时间",
        semi_cut_seq: "半成品切割序列",
        quality_code: "质量编码",
        scarfed_status: "剪裁状态",
        scarfed_qty: "斜接数量",
        semi_type: "半成品类型",
        defect:  "缺陷",
        defect_qty: "缺陷数量",
        comment: "批注",

        current_holds: "当前暂停原因",
        hold_code: "暂停原因编号",
        hold_type: "暂停类型",
        hold_name: "暂停原因名称",
        no_data_available: "没有可用的数据",
    },
}