export default{
    organization_settings:"组织设置",
    type:"类型",
    organization_status:"组织状态",
    jobs:"# job数量",
    maxjobs:"最大Job数",
    worker:"# worker数量",
    max_workers:"最大worker数量",
    team:"团队数量",
    max_team:"最大团队数量",
    job_change_callback:"job变更回调",
    job_change_callback_url: "job变更回调链接",
    working_calendar:"工作日历",
    worker_flex_form_schema:"worker配置参数",
    default_worker_flex_form_data:'默认worker配置参数',
    order_flex_form_schema:"order配置参数",
    default_order_flex_form_data:"默认order配置参数",
    job_flex_form_schema:"job配置参数",
    default_job_flex_form_data:"默认Job配置参数",
    system_settings:"系统设置",
}