export default {
  table: {
    test_sample_code: "测试样本",
    test_sample_part: "测试示例",
    ref_code: "参考编码",
    mill_code: "工厂",
    spec_code: "规格",
    short_name: "简称",
    rolling_code: "轧制计划",
    cast_code: "铸件",
    runout_code: "钢坯",
    finished_product: "成品",
    area_code: "区域",
    size: "尺寸",
    reason: "原因",
    comment: "备注 ",
    status: "状态",
    reason_code: "原因",
    product_name: "产品名称",
    sample_thickness: "样本厚度",
    sample_info: "样本信息",
    retest:  "重新测试",
    orientation: "方向",
    standard: "标准",
    inspector:  "检查员",
    inspector_longname: "检查员全名",
    source: "来源",
    created_at: "创建时间",
    start_date: "开始日期",
    end_date: "结束日期",
    test:  "测试",
    tensile: "拉伸",
    impact: "冲击",
    chemical: "化学",
    through_thickness: "穿透厚度",
    desc: "描述信息",
    cut: "切割",
    receive: "接收",
  },
  new: {
    add: "添加",
    desc: "测试样本详细信息",
    test_sample_details: "测试样本详细信息",
    reson_code: "原因",
    concast_code: "连铸",
    spec_details: "规格详细信息",
    spec_short_name: "规格简称",
    spec_full_name: "规格全名",
    cut_code: "切割",
  },
  test: "测试",
  delete: {
    delete_title: "Delete Service?",
    comform_delete: "Are you sure you would like to delete this service?"
  },

  search_hint: "Search by code, name, description",

  edit: {
    service_code: "Service Code",
    service_name: "Service Name",
    description: "Description",
    description_hint: "A description for your service."
  }
};
