export default {
  table: {
    search_by_section_size_code: "按截面尺寸代码搜索",
    test_type: "测试类型",
    date_range: "日期",
    confirm: "确认",
    when: "时间",
    test_id: "测试编号",
    created_by: "创建人",
    created_date: "创建日期",
    testing_machine: "测试机",
    section_size_code: "截面尺寸代码",
    semi: "半成品",
    kgm: "千克米",
    impact_temp_c: "冲击温度 (°C)",
    impact_temp_f: "冲击温度 (°F)",
    impact_temp_units: "冲击温度单位",
    impact_energy_1_j: "冲击能量 1 (J)",
    impact_energy_2_j: "冲击能量 2 (J)",
    impact_energy_3_j: "冲击能量 3 (J)",
    impact_energy_average_j: "冲击能量平均值 (J)",
    impact_energy_1_f: "冲击能量 1 (F)",
    impact_energy_2_f: "冲击能量 2 (F)",
    impact_energy_3_f: "冲击能量 3 (F)",
    impact_energy_average_f: "冲击能量平均值 (F)",
    impact_shear_1: "冲击剪切 1",
    impact_shear_2: "冲击剪切 2",
    impact_shear_3: "冲击剪切 3",
    impact_shear_average: "冲击剪切平均值",
    impact_impact_units: "冲击单位",
    impact_energy_units: "冲击能量单位",
    yield_low: "屈服强度低 (MPa)",
    r1_temp_c: "R1 冲击温度(℃)",
    r1_temp_f: "R1 冲击温度(℉)",
    r1_energy_1_j: "R1 冲击能量 1(J)",
    r1_energy_2_j: "R1 冲击能量 2(J)",
    r1_energy_3_j: "R1 冲击能量 3(J)",
    r1_energy_average_j: "R1 平均冲击能量(J)",
    r1_energy_1_f: "R1 冲击能量 1(ft·lbf)",
    r1_energy_2_f: "R1 冲击能量 2(ft·lbf)",
    r1_energy_3_f: "R1 冲击能量 3(ft·lbf)",
    r1_energy_average_f: "R1 平均冲击能量(ft·lbf)",
    r1_shear_1: "R1 剪切面积 1",
    r1_shear_2: "R1 剪切面积 2",
    r1_shear_3: "R1 剪切面积 3",
    r1_shear_average: "R1 平均剪切面积",
    r1_temp_units: "R1 温度单位",
    r1_impact_units: "R1 冲击单位",
    r1_energy_units: "R1 能量单位",
    heat_treated_by: "弯曲试样热处理人",
    tested_by: "弯曲试样测试人",
    result_1: "弯曲试验结果 1",
    result_2: "弯曲试验结果 2",
    type: "洁净度类型",
    k_number: "洁净度 K 编号",
    k_value: "洁净度 K 值",
    bhn_min_max: "硬度 BHN 最小/最大值",
    ball_size_mm: "硬度钢球直径(mm)",
    load_kg: "硬度加载力(kg)",
    hardness_1: "硬度值 1",
    hardness_2: "硬度值 2",
    hardness_3: "硬度值 3",
    hardness_4: "硬度值 4",
    hardness_5: "硬度值 5",
    hardness_av: "平均硬度值",
    decarburisation_min: "脱碳层最小值",
    decarburisation_max: "脱碳层最大值",
    decarburisation: "脱碳层厚度",
    spec_test: "氢含量规范测试",
    rail_grade: "氢含量轨道钢等级",
    max_test: "氢含量最大值测试",
    max_resistivity: "最大电阻率",
    temperature: "电阻率测试温度",
    temp: "电阻率温度",
    distance: "电阻率测试距离",
    volt: "电阻率电压",
    current: "电阻率电流",
    resistivity: "电阻率",
    humidity: "电阻率测试湿度",
    sulphur_rail_grade: "硫含量轨道钢等级",
    tested_thickness: "拉伸试样厚度",
    tested_width: "拉伸试样宽度",
    tested_diameter: "拉伸试样直径",
    yield_tt0_5: "拉伸屈服强度 Rt0.5(MPa)",
    yield_high: "拉伸屈服高值(MPa)",
    yield_rp0_2: "拉伸屈服强度 Rp0.2(MPa)",
    yield_low: "拉伸屈服低值(MPa)",
    elongation_code: "拉伸伸长率代码(%)",
    elongation_a565: "拉伸伸长率 A5×65(%)",
    elongation_a200: "拉伸伸长率 A200(%)",
    elongation_a50: "拉伸伸长率 A50(%)",
    elongation_8: "拉伸伸长率 8 英寸(%)",
    elongation_2: "拉伸伸长率 2 英寸(%)",
    elongation_a80: "拉伸伸长率 A80(%)",
    r1_tested_thickness: "R1 拉伸试样厚度",
    r1_tested_width: "R1 拉伸试样宽度",
    r1_tested_diameter: "R1 拉伸试样直径",
    r1_yield_tt0_5: "R1 屈服强度 Rt0.5(MPa)",
    r1_yield_high: "R1 屈服高值(MPa)",
    r1_yield_rp0_2: "R1 屈服强度 Rp0.2(MPa)",
    r1_yield_low: "R1 屈服低值(MPa)",
    r1_elongation_code: "R1 拉伸伸长率代码(%)",
    r1_elongation_a565: "R1 拉伸伸长率 A5×65(%)",
    r1_elongation_a200: "R1 拉伸伸长率 A200(%)",
    r1_elongation_a50: "R1 拉伸伸长率 A50(%)",
    r1_elongation_8: "R1 拉伸伸长率 8 英寸(%)",
    r1_elongation_2: "R1 拉伸伸长率 2 英寸(%)",
    r1_elongation_a80: "R1 拉伸伸长率 A80(%)",
    r2_tested_thickness: "R2 拉伸试样厚度",
    r2_tested_width: "R2 拉伸试样宽度",
    r2_tested_diameter: "R2 拉伸试样直径",
    r2_yield_tt0_5: "R2 屈服强度 Rt0.5(MPa)",
    r2_yield_high: "R2 屈服高值(MPa)",
    r2_yield_rp0_2: "R2 屈服强度 Rp0.2(MPa)",
    r2_yield_low: "R2 屈服低值(MPa)",

    elongation_code: "延伸率代码 (%)",
    elongation_a565: "延伸率 A565 (%)",
    elongation_a200: "延伸率 A200 (%)",
    elongation_a50: "延伸率 A50 (%)",
    elongation_8: "延伸率 8 英寸 (%)",
    elongation_2: "延伸率 2 英寸 (%)",
    elongation_a80: "延伸率 A80 (%)",
    r1_tested_thickness: "R1 测试厚度",
    r1_tested_width: "R1 测试宽度",
    r1_tested_diameter: "R1 测试直径",
    r1_yield_tt0_5: "R1 屈服强度 Rt0.5 (MPa)",
    r1_yield_high: "R1 屈服强度高 (MPa)",
    r1_yield_rp0_2: "R1 屈服强度 Rp0.2 (MPa)",
    r1_yield_low: "R1 屈服强度低 (MPa)",
    r1_elongation_code: "R1 延伸率代码 (%)",
    r1_elongation_a565: "R1 延伸率 A565 (%)",
    r1_elongation_a200: "R1 延伸率 A200 (%)",
    r1_elongation_a50: "R1 延伸率 A50 (%)",
    r1_elongation_8: "R1 延伸率 8 英寸 (%)",
    r1_elongation_2: "R1 延伸率 2 英寸 (%)",
    r1_elongation_a80: "R1 延伸率 A80 (%)",
    r2_tested_thickness: "R2 测试厚度",
    r2_tested_width: "R2 测试宽度",
    r2_tested_diameter: "R2 测试直径",
    r2_yield_tt0_5: "R2 屈服强度 Rt0.5 (MPa)",
    r2_yield_high: "R2 屈服强度高 (MPa)",
    r2_yield_rp0_2: "R2 屈服强度 Rp0.2 (MPa)",
    r2_yield_low: "R2 屈服强度低 (MPa)",
    r2_elongation_code: "R2 延伸率代码 (%)",
    r2_elongation_a565: "R2 延伸率 A565 (%)",
    r2_elongation_a200: "R2 延伸率 A200 (%)",
    r2_elongation_a50: "R2 延伸率 A50 (%)",
    r2_elongation_8: "R2 延伸率 8 英寸 (%)",
    r2_elongation_2: "R2 延伸率 2 英寸 (%)",
    r2_elongation_a80: "R2 延伸率 A80 (%)",
    tensile_uts_mpa: "拉伸抗拉强度 (UTS) (MPa)",
    r1_tensile_uts_mpa: "R1 拉伸抗拉强度 (UTS) (MPa)",
    r2_tensile_uts_mpa: "R2 拉伸抗拉强度 (UTS) (MPa)",
    result_c: "Prodan 测试结果 C",
    result_si: "Prodan 测试结果 Si",
    result_mn: "Prodan 测试结果 Mn",
    result_p: "Prodan 测试结果 P",
    result_s: "Prodan 测试结果 S",
    result_cr: "Prodan 测试结果 Cr",
    result_mo: "Prodan 测试结果 Mo",
    result_ni: "Prodan 测试结果 Ni",
    result_al: "Prodan 测试结果 Al",
    result_b: "Prodan 测试结果 B",
    result_co: "Prodan 测试结果 Co",
    result_cu: "Prodan 测试结果 Cu",
    result_nb: "Prodan 测试结果 Nb",
    result_sn: "Prodan 测试结果 Sn",
    result_ti: "Prodan 测试结果 Ti",
    result_v: "Prodan 测试结果 V",
    result_ca: "Prodan 测试结果 Ca",
    result_n2: "Prodan 测试结果 N2",
    result_o: "Prodan 测试结果 O",
    result_h: "Prodan 测试结果 H",
    result_sal: "Prodan 测试结果 Sal",
    result_as: "Prodan 测试结果 As",
    result_bi: "Prodan 测试结果 Bi",
    result_ce: "Prodan 测试结果 Ce",
    result_pb: "Prodan 测试结果 Pb",
    result_sb: "Prodan 测试结果 Sb",
    result_w: "Prodan 测试结果 W",
    result_zn: "Prodan 测试结果 Zn",
    result_zr: "Prodan 测试结果 Zr",
    uuid: "唯一标识码",
    confirm_at: "确认时间",
    confirm_by: "确认人",
    created_at: "创建时间",
    created_by: "创建人",
    update_name: "更新者",
    updated_at: "更新时间",
    update_by: "更新人"
    
  },
  test: "Test",
  delete: {
    delete_title: "Delete Service?",
    comform_delete: "Are you sure you would like to delete this service?"
  },

  search_hint: "Search by code, name, description",

  edit: {
    service_code: "Service Code",
    service_name: "Service Name",
    description: "Description",
    description_hint: "A description for your service."
  }
};
