export default {
  table: {
    search_by_test_code: "根据测试代码搜索",
    update: "更新",
    type: "类型",
    result_status: "结果状态",
    test_status: "测试状态",
    standard: "标准",
    time_range: "时间范围",
    auto_pass: "自动通过",
    test_code: "测试",
    long_cast_code: "长铸",
    cast_code: "铸件",
    ref: "参考",
    sample: "部件",
    runout: "钢坯",
    rolling: "轧制计划",
    spec: "规格",
    standard: "标准",
    inspector_1: "检验员 1",
    inspector_2: "检验员 2",
    inspector_3: "检验员 3",
    inspector_4: "检验员 4",
    status: "状态",
    print_status: "打印状态",
    tester_initials: "测试员首字母",
    kg: "千克/米",
    tensile_loc: "拉伸位置",
    yield: "屈服强度",
    uts: "极限抗拉强度 (MPa)",
    elongation: "延伸率",
    elongation_code: "延伸率值",
    yield_ratio: "屈服强度/极限抗拉强度比",
    impart_temp: "赋能温度",
    impart_unit: "赋能单位",
    temp_unit: "温度单位",
    energy_1:  "能量 1",
    energy_2:  "能量 2",
    energy_3:  "能量 3",
    energy_average:  "能量平均值",
    bend_result: "弯曲结果",
    created_at: "创建时间",
    updated_at: "更新时间",
    save: "保存",
  },
  detail: {
    covered_products: "覆盖产品",
    finished_product_code: "成品",
    test_code: "检测",
    covered_weight_kg: "覆盖重量(kg)",
    retest_2: "二次检测",
    covered_quantity: "覆盖数量",
    cast: "炉号",
    type: "类型",
    temp: "温度(°C)",
    nominated_time: "指定时间",
    test_code: "测试代码",
    test_result: "测试结果",
    test_ref: "测试参考",
    test_ref_rt2: "RT2 测试参考",
    long_cast_code: "长铸代码",
    status: "状态",
    print_status: "打印状态",
    test_standard: "测试标准",
    type: "类型",
    spec_requirements: "规格要求",
    test_impact: "测试影响",
    check_digit_0: "校验位 0",
    testing_machine: "测试机",
    temperature_f: "温度 (°F)",
    temperature_c: "温度 (°C)",
    energy_1_j: "能量 1 (J)",
    energy_2_j: "能量 2 (J)",
    energy_3_j: "能量 3 (J)",
    energy_average_j: "平均能量 (J)",
    energy_1_f: "能量 1 (F)",
    energy_2_f: "能量 2 (F)",
    energy_3_f: "能量 3 (F)",
    energy_average_f: "平均能量 (F)",
    shear_1: "剪切 1",
    shear_2: "剪切 2",
    shear_3: "剪切 3",
    shear_average: "剪切平均值",
    tested_by: "测试人员",
    impact_size: "冲击尺寸",
    retest_1: "重测 1",
    check_digit_1: "校验位 1",
    check_digit_2: "校验位 2",
    energy_j: "能量 (J)",
    energy_average_j: "平均能量 (J)",
    energy_1_f: "能量 (F)",
    energy_average_f: "平均能量 (F)",
    spec_unit: "规格单位",
    avg_min:"平均最小值",
    ind_max:"单个最大值",
    tensile_min: "抗拉最小值",
    tensile_max: "抗拉最大值",
    yield_min: "屈服最小值",
    yield_max: "屈服最大值",
    y_min: "Y/T 最小值",
    y_max: "Y/T 最大值",
    elongation_code: "延伸值",
    elongation_min: "延伸最小值",
    test_tensile_result: "测试抗拉结果",
    measured_thickness: "测量厚度",
    measured_width: "测量宽度",
    measured_diameter: "测量直径",
    yield_rt: "屈服 Rt0.5 (MPa)",
    yield_high: "屈服高 (MPa)",
    yield_rp: "屈服 Rp0.2 (MPa)",
    yield_low: "屈服低 (MPa)",
    yield: "屈服 (MPa)",
    uts_mpa: "抗拉强度 (MPa)",
    elongation: "延伸率 (%)",
    elongation_a565: "延伸率 A565 (%)",
    elongation_a200: "延伸率 A200 (%)",
    elongation_a50: "延伸率 A50 (%)",
    elongation_a80: "延伸率 A80 (%)",
    elongation_8_in: "延伸率 8英寸 (%)",
    elongation_2_in: "延伸率 2英寸 (%)",
    testing_machine: "测试机",
    reduction_of_area: "面积收缩率",
    cross_seational_area: "横截面积",
    area: "面积",
    test_standard: "测试标准",
    tested_by: "测试人员",
    test_bend: "弯曲测试",
    code: "代码",
    heat_treated_by: "热处理方式",
    result: "结果",
    spec_requirements: "规格要求",
    k_value_max: "K值最大值",
    k_number: "K 编号",
    test_requirements: "测试要求",
    k_oxide: "K 氧化物",
    decarb_value_max: "去碳最大值",
    section: "截面",
    section_size_code: "截面尺寸代码",
    bloom: "铸坯",
    inspection_authority_code: "检验机构",
    kg: "千克",
    max: "最大值",
    decarburisation: "去碳",
    decarburisation_min: "去碳最小值",
    decarburisation_max: "去碳最大值",
    decarb: "去碳",
    test_hardness: "硬度测试",
    bhn: "BHN 最小/最大值",
    ball_size: "钢球尺寸 (mm)",
    load_kg: "载重 (Kg)",
    hardness_1: "硬度 1",
    hardness_2: "硬度 2",
    hardness_3: "硬度 3",
    hardness_4: "硬度 4",
    hardness_5: "硬度 5",
    hardness_avg_unit: "硬度平均单位 (HBW)",
    test_hydrogen: "氢气测试",
    max_test: "最大测试值",
    rail_grade: "轨道钢等级",
    spec_test: "规格测试",
    result_c: "结果 C (碳)",
    result_si: "结果 Si (硅)",
    result_mn: "结果 Mn (锰)",
    result_p: "结果 P (磷)",
    result_s: "结果 S (硫)",
    result_cr: "结果 Cr (铬)",
    result_mo: "结果 Mo (钼)",
    result_ni: "结果 Ni (镍)",
    result_al: "结果 Al (铝)",
    result_cu: "结果 Cu (铜)",
    result_co: "结果 Co (钴)",
    result_b: "结果 B (硼)",
    result_nb: "结果 Nb (铌)",
    result_v: "结果 V (钒)",
    result_sn: "结果 Sn (锡)",
    result_ti: "结果 Ti (钛)",
    result_ca: "结果 Ca (钙)",
    result_n2: "结果 N2 (氮气)",
    result_o: "结果 O (氧)",
    result_h: "结果 H (氢)",
    result_sal: "结果 Sal (盐)",
    result_as: "结果 As (砷)",
    result_bi: "结果 Bi (铋)",
    result_ce: "结果 Ce (铈)",
    result_pb: "结果 Pb (铅)",
    result_sb: "结果 Sb (锑)",
    result_w: "结果 W (钨)",
    result_zn: "结果 Zn (锌)",
    result_zr: "结果 Zr (锆)",
    max_resistivity: "最大电阻率",
    test_resistivity: "电阻率测试",
    temperature: "温度 (°C)",
    humidity: "湿度 (%)",
    distance: "距离 (mm)",
    voit: "电压 (V)",
    current: "电流 (A)",
    resistivity_mo: "电阻率 (mo·cm)",
    correction_factor: "修正系数",
    correct_resistivity: "修正电阻率 (mo·cm)",
    sulphur_print_max: "硫磺印记最大值",
    d_val: "D 值",
    in_spec: "符合规格",
    test_decarburization: "去碳测试",
    test_prodan: "产品分析测试",
    test_sulphur: "硫含量测试",
    updated_at: "更新时间",
    updater: "更新者",
    update_reason: "更新原因",
    tester: "测试者",
    created_at: "创建时间",
    comment: "评论",
    
  },
  test: "测试",
  delete: {
    delete_title: "Delete Service?",
    comform_delete: "Are you sure you would like to delete this service?"
  },

  search_hint: "Search by code, name, description",

  edit: {
    service_code: "Service Code",
    service_name: "Service Name",
    description: "Description",
    description_hint: "A description for your service."
  }
};
